


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Marking_System(object):
    def setupUi(self, Marking_System):
        Marking_System.setObjectName("Marking_System")
        Marking_System.resize(615, 634)
        self.centralwidget = QtWidgets.QWidget(Marking_System)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 140, 251, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_manual = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_manual.setObjectName("btn_manual")
        self.verticalLayout.addWidget(self.btn_manual)
        self.btn_machine = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_machine.setObjectName("btn_machine")
        self.verticalLayout.addWidget(self.btn_machine)
        self.btn_analysis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_analysis.setObjectName("btn_analysis")
        self.verticalLayout.addWidget(self.btn_analysis)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 60, 501, 41))
        self.label.setObjectName("label")
        Marking_System.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Marking_System)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 615, 26))
        self.menubar.setObjectName("menubar")
        self.menu_mode_select = QtWidgets.QMenu(self.menubar)
        self.menu_mode_select.setObjectName("menu_mode_select")
        self.menu_note = QtWidgets.QMenu(self.menubar)
        self.menu_note.setObjectName("menu_note")
        Marking_System.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Marking_System)
        self.statusbar.setObjectName("statusbar")
        Marking_System.setStatusBar(self.statusbar)
        self.actionmanual_marking = QtWidgets.QAction(Marking_System)
        self.actionmanual_marking.setObjectName("actionmanual_marking")
        self.actionmachine_marking = QtWidgets.QAction(Marking_System)
        self.actionmachine_marking.setObjectName("actionmachine_marking")
        self.actionhelp = QtWidgets.QAction(Marking_System)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(Marking_System)
        self.actionabout.setObjectName("actionabout")
        self.actionanalysis = QtWidgets.QAction(Marking_System)
        self.actionanalysis.setObjectName("actionanalysis")
        self.actionpre_deal = QtWidgets.QAction(Marking_System)
        self.actionpre_deal.setObjectName("actionpre_deal")
        self.menu_mode_select.addAction(self.actionmanual_marking)
        self.menu_mode_select.addAction(self.actionmachine_marking)
        self.menu_mode_select.addAction(self.actionanalysis)
        self.menu_note.addAction(self.actionhelp)
        self.menu_note.addAction(self.actionabout)
        self.menubar.addAction(self.menu_mode_select.menuAction())
        self.menubar.addAction(self.menu_note.menuAction())

        self.retranslateUi(Marking_System)




        QtCore.QMetaObject.connectSlotsByName(Marking_System)

    def retranslateUi(self, Marking_System):
        _translate = QtCore.QCoreApplication.translate
        Marking_System.setWindowTitle(_translate("Marking_System", "MainWindow"))
        self.btn_manual.setText(_translate("Marking_System", "人工识别"))
        self.btn_machine.setText(_translate("Marking_System", "机器识别"))
        self.btn_analysis.setText(_translate("Marking_System", "数据分析"))
        self.label.setText(_translate("Marking_System", "欢 迎 使 用 视 频 情 感 标 注 系 统 "))
        self.menu_mode_select.setTitle(_translate("Marking_System", "&菜单"))
        self.menu_note.setTitle(_translate("Marking_System", "&说明"))
        self.actionmanual_marking.setText(_translate("Marking_System", "Manual marking"))
        self.actionmachine_marking.setText(_translate("Marking_System", "Machine marking"))
        self.actionhelp.setText(_translate("Marking_System", "help"))
        self.actionabout.setText(_translate("Marking_System", "about"))
        self.actionanalysis.setText(_translate("Marking_System", "Analysis"))
        self.actionpre_deal.setText(_translate("Marking_System", "pre_making"))
        self.actionabout.triggered.connect(lambda: Marking_System.about_us())
        self.actionhelp.triggered.connect(lambda: Marking_System.help())
        self.actionmachine_marking.triggered.connect(lambda: Marking_System.jump_to_machine())
        self.actionmanual_marking.triggered.connect(lambda: Marking_System.jump_to_manual())
        self.actionanalysis.triggered.connect(lambda: Marking_System.jump_to_analysis())
        self.btn_manual.clicked.connect(lambda: Marking_System.jump_to_manual())
        # self.btn_machine.clicked.connect(lambda: Marking_System.jump_to_machine())
        # self.btn_analysis.clicked.connect(lambda: Marking_System.jump_to_analysis())
